POST http://127.0.0.1:5000/api/user/login
Content-Type: application/json
Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MjM4ODA3NCwianRpIjoiNTVmZTU0ZjctNWJjYi00ODQzLTkzMjUtNWIxMGFlNGYyNDk1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVzZXJfMSIsIm5iZiI6MTc0MjM4ODA3NCwiY3NyZiI6IjgxN2Y2MzY0LTU5ZDEtNDBkYS1iM2U0LWZjNDlhMWY3YTIxYiIsImV4cCI6MTc0MjM4ODk3NH0.jwW7RwA_49HiQ4H6T5bfwhMdHbTnLy0-rAwGE_9Rt3w>

{
    "account_id": 1,
    "reference": "DEP001",
    "description": "Salary",
    "amount": 500.00,
    "category": "income"
}