POST http://127.0.0.1:5000/api/transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoidXNlciIsImV4cCI6MTc0MjU2NjQ0Nn0.YANghBLaVgBcwliSdhc2iAnYksvuTw-332MgamQTT4I

{
    "account_id": 1,
    "reference": "TX003",
    "description": "Test withdrawal",
    "amount": 1000.00,
    "type": "withdrawal",
    "category": "test"
}